name: socnet
description: A Mobile Frontend for the Socio App

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  equatable: ^2.0.3
  shared_preferences: ^2.0.0-nullsafety
  http: ^0.13.4
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  get_it: ^7.2.0
  uuid: ^3.0.6
  image_picker: ^0.8.5
  image_cropper: ^2.0.2
  fake_async: ^1.2.0

dev_dependencies:
  english_words: ^4.0.0
  mocktail: ^0.3.0
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

